-- Ma trận phân quyền: vai trò -> quyền (GĐ2).
--
-- DANH SÁCH quyền là hằng số trong code (apps/web/lib/nen-tang/quyen.ts) — một mã
-- quyền chỉ có nghĩa khi CÓ CHỖ TRONG CODE kiểm tra nó. Bảng này chỉ lưu Ô NÀO
-- ĐƯỢC TICK, không lưu danh sách mã.
--
-- 155 ô khởi tạo dưới đây SINH THẲNG TỪ code (MAC_DINH), không gõ tay ⇒ DB và code
-- không thể lệch nhau. Giá trị = hành vi HÔM NAY, trừ 3 ô CEO chủ động đổi 20/08
-- (xem spec §6.1). GĐ2 chạy SONG SONG: bảng này chỉ được HỎI Ý KIẾN và ghi log lệch,
-- luật quyết định vẫn là laAdmin()/laQuanLy() cũ. Bật thật ở GĐ3.
--
-- Spec: docs/superpowers/specs/2026-08-20-nen-tang-tai-khoan-phan-quyen-design.md §6

create table if not exists public.quyen_vai_tro (
  vai_tro  text not null,
  ma_quyen text not null,
  primary key (vai_tro, ma_quyen)
);

comment on table public.quyen_vai_tro is
  'Ma trận phân quyền vai trò x quyền. Danh sách mã quyền nằm ở apps/web/lib/nen-tang/quyen.ts, KHÔNG tự thêm mã ở đây.';

alter table public.quyen_vai_tro enable row level security;
-- 0 policy: chỉ service_role (đã qua gác cổng tầng app) đọc/ghi được, giống mọi bảng khác.

insert into public.quyen_vai_tro (vai_tro, ma_quyen) values
  ('ceo', 'cs.khach.xem'),
  ('ceo', 'cs.may.xem'),
  ('ceo', 'cs.ticket.xem'),
  ('ceo', 'cs.bao_tri.xem'),
  ('ceo', 'cs.ky_thuat.lich_cua_toi'),
  ('ceo', 'cs.bao_cao.doanh_so'),
  ('ceo', 'sales.don.xem'),
  ('ceo', 'he_thong.nhan_su.xem'),
  ('ceo', 'he_thong.nhat_ky'),
  ('admin', 'cs.khach.xem'),
  ('admin', 'cs.khach.sua'),
  ('admin', 'cs.khach.xin_xoa'),
  ('admin', 'cs.khach.gop'),
  ('admin', 'cs.khach.duyet_cho'),
  ('admin', 'cs.khach.xin_xuat'),
  ('admin', 'cs.khach.duyet_xuat'),
  ('admin', 'cs.khach.xoa_hang_loat'),
  ('admin', 'cs.may.xem'),
  ('admin', 'cs.may.kich_hoat_bh'),
  ('admin', 'cs.may.lap_thu_doi'),
  ('admin', 'cs.serial.kho'),
  ('admin', 'cs.serial.duyet'),
  ('admin', 'cs.may.thay_loi'),
  ('admin', 'cs.may.trang_thai'),
  ('admin', 'cs.ticket.xem'),
  ('admin', 'cs.ticket.tao_sua'),
  ('admin', 'cs.ticket.chi_phi'),
  ('admin', 'cs.ticket.nhom_loi'),
  ('admin', 'cs.bao_tri.xem'),
  ('admin', 'cs.bao_tri.ghi_ket_qua'),
  ('admin', 'cs.bao_tri.tao_plan'),
  ('admin', 'cs.bao_tri.duyet_plan'),
  ('admin', 'cs.ky_thuat.lich_cua_toi'),
  ('admin', 'cs.ky_thuat.ho_so'),
  ('admin', 'cs.ky_thuat.xep_lich'),
  ('admin', 'cs.ky_thuat.tai_khoan'),
  ('admin', 'cs.bao_cao.xuat'),
  ('admin', 'cs.bao_cao.doanh_so'),
  ('admin', 'cs.yeu_cau.gui'),
  ('admin', 'cs.yeu_cau.tu_choi'),
  ('admin', 'cs.yeu_cau.duyet'),
  ('admin', 'cs.hang_loat.cap_nhat'),
  ('admin', 'work.viec.xem_tao'),
  ('admin', 'work.viec.giao'),
  ('admin', 'work.luat_tu_sinh'),
  ('admin', 'sales.don.xem'),
  ('admin', 'sales.don.ghi'),
  ('admin', 'he_thong.nhan_su.xem'),
  ('admin', 'he_thong.nhan_su.sua'),
  ('admin', 'he_thong.phan_quyen'),
  ('admin', 'he_thong.nhat_ky'),
  ('admin', 'he_thong.catalog'),
  ('admin', 'he_thong.kenh'),
  ('admin', 'he_thong.view_chung'),
  ('kt_giam_doc', 'cs.ky_thuat.lich_cua_toi'),
  ('kt_giam_doc', 'work.viec.xem_tao'),
  ('kt_giam_doc', 'work.viec.giao'),
  ('ky_thuat', 'cs.khach.xem'),
  ('ky_thuat', 'cs.khach.sua'),
  ('ky_thuat', 'cs.khach.xin_xoa'),
  ('ky_thuat', 'cs.khach.xin_xuat'),
  ('ky_thuat', 'cs.may.xem'),
  ('ky_thuat', 'cs.may.kich_hoat_bh'),
  ('ky_thuat', 'cs.may.thay_loi'),
  ('ky_thuat', 'cs.ticket.xem'),
  ('ky_thuat', 'cs.ticket.tao_sua'),
  ('ky_thuat', 'cs.ticket.chi_phi'),
  ('ky_thuat', 'cs.bao_tri.xem'),
  ('ky_thuat', 'cs.bao_tri.ghi_ket_qua'),
  ('ky_thuat', 'cs.bao_tri.tao_plan'),
  ('ky_thuat', 'cs.ky_thuat.lich_cua_toi'),
  ('ky_thuat', 'cs.bao_cao.doanh_so'),
  ('ky_thuat', 'cs.yeu_cau.gui'),
  ('ky_thuat', 'work.viec.xem_tao'),
  ('ky_thuat', 'work.viec.giao'),
  ('ky_thuat', 'he_thong.kenh'),
  ('ctv_lap_dat', 'cs.ky_thuat.lich_cua_toi'),
  ('ctv_lap_dat', 'work.viec.xem_tao'),
  ('ctv_lap_dat', 'work.viec.giao'),
  ('cs_manager', 'cs.khach.xem'),
  ('cs_manager', 'cs.khach.sua'),
  ('cs_manager', 'cs.khach.xin_xoa'),
  ('cs_manager', 'cs.khach.gop'),
  ('cs_manager', 'cs.khach.duyet_cho'),
  ('cs_manager', 'cs.khach.xin_xuat'),
  ('cs_manager', 'cs.khach.duyet_xuat'),
  ('cs_manager', 'cs.may.xem'),
  ('cs_manager', 'cs.may.kich_hoat_bh'),
  ('cs_manager', 'cs.may.lap_thu_doi'),
  ('cs_manager', 'cs.serial.kho'),
  ('cs_manager', 'cs.serial.duyet'),
  ('cs_manager', 'cs.may.thay_loi'),
  ('cs_manager', 'cs.may.trang_thai'),
  ('cs_manager', 'cs.ticket.xem'),
  ('cs_manager', 'cs.ticket.tao_sua'),
  ('cs_manager', 'cs.ticket.chi_phi'),
  ('cs_manager', 'cs.ticket.nhom_loi'),
  ('cs_manager', 'cs.bao_tri.xem'),
  ('cs_manager', 'cs.bao_tri.ghi_ket_qua'),
  ('cs_manager', 'cs.bao_tri.tao_plan'),
  ('cs_manager', 'cs.bao_tri.duyet_plan'),
  ('cs_manager', 'cs.ky_thuat.lich_cua_toi'),
  ('cs_manager', 'cs.ky_thuat.ho_so'),
  ('cs_manager', 'cs.ky_thuat.xep_lich'),
  ('cs_manager', 'cs.bao_cao.xuat'),
  ('cs_manager', 'cs.bao_cao.doanh_so'),
  ('cs_manager', 'cs.yeu_cau.gui'),
  ('cs_manager', 'cs.yeu_cau.tu_choi'),
  ('cs_manager', 'cs.hang_loat.cap_nhat'),
  ('cs_manager', 'work.viec.xem_tao'),
  ('cs_manager', 'work.viec.giao'),
  ('cs_manager', 'work.luat_tu_sinh'),
  ('cs_manager', 'he_thong.kenh'),
  ('cs_manager', 'he_thong.view_chung'),
  ('cs', 'cs.khach.xem'),
  ('cs', 'cs.khach.sua'),
  ('cs', 'cs.khach.xin_xoa'),
  ('cs', 'cs.khach.xin_xuat'),
  ('cs', 'cs.may.xem'),
  ('cs', 'cs.may.kich_hoat_bh'),
  ('cs', 'cs.may.thay_loi'),
  ('cs', 'cs.ticket.xem'),
  ('cs', 'cs.ticket.tao_sua'),
  ('cs', 'cs.ticket.chi_phi'),
  ('cs', 'cs.bao_tri.xem'),
  ('cs', 'cs.bao_tri.ghi_ket_qua'),
  ('cs', 'cs.bao_tri.tao_plan'),
  ('cs', 'cs.ky_thuat.lich_cua_toi'),
  ('cs', 'cs.bao_cao.doanh_so'),
  ('cs', 'cs.yeu_cau.gui'),
  ('cs', 'work.viec.xem_tao'),
  ('cs', 'work.viec.giao'),
  ('cs', 'he_thong.kenh'),
  ('sales_manager', 'cs.ky_thuat.lich_cua_toi'),
  ('sales_manager', 'work.viec.xem_tao'),
  ('sales_manager', 'work.viec.giao'),
  ('sales_manager', 'sales.don.xem'),
  ('sales_manager', 'sales.don.ghi'),
  ('sales', 'cs.ky_thuat.lich_cua_toi'),
  ('sales', 'work.viec.xem_tao'),
  ('sales', 'work.viec.giao'),
  ('sales', 'sales.don.xem'),
  ('sales', 'sales.don.ghi'),
  ('marketing', 'cs.ky_thuat.lich_cua_toi'),
  ('marketing', 'work.viec.xem_tao'),
  ('marketing', 'work.viec.giao'),
  ('kho', 'cs.ky_thuat.lich_cua_toi'),
  ('kho', 'work.viec.xem_tao'),
  ('kho', 'work.viec.giao'),
  ('ke_toan', 'cs.ky_thuat.lich_cua_toi'),
  ('ke_toan', 'work.viec.xem_tao'),
  ('ke_toan', 'work.viec.giao'),
  ('tai_chinh', 'cs.ky_thuat.lich_cua_toi'),
  ('tai_chinh', 'work.viec.xem_tao'),
  ('tai_chinh', 'work.viec.giao')
on conflict do nothing;
