-- Seed lại ma trận theo 50 quyền — đọc lại code khi nối GĐ2-B thì lộ 3 chỗ SAI
-- trong đợt trước (tôi phân loại bằng grep, chưa đọc thân hàm):
--
--  1. `duyetYeuCau` gác bằng laQuanLy() chứ KHÔNG phải laAdmin ⇒ Trưởng CSKH
--     DUYỆT được yêu cầu sửa. Đợt trước ghi nhầm là chỉ admin.
--     Nhưng có luật con: duyệt XOÁ hồ sơ khách thì đòi thêm laAdmin ⇒ tách quyền
--     mới `cs.khach.duyet_xoa` (chỉ admin).
--  2. `guiYeuCauThayDoi` là bộ ĐỊNH TUYẾN, không phải cổng chặn: quản lý sửa ÁP
--     THẲNG, người khác thì vào hàng chờ ⇒ quyền mới `cs.yeu_cau.ap_thang`.
--  3. `searchTickets` dùng laQuanLy để quyết PHẠM VI nhìn thấy (nhân viên chỉ
--     thấy ticket của mình + ticket chưa ai nhận) ⇒ quyền mới `cs.ticket.xem_tat_ca`.
--
-- Gộp `cs.yeu_cau.tu_choi` vào `cs.yeu_cau.duyet` (cùng gác laQuanLy), thêm
-- `cs.yeu_cau.xem`. Tổng 47 -> 50 quyền.
--
-- Vẫn seed lại toàn bộ: GĐ2 đang chạy thử, CEO chưa chỉnh tay ô nào.

delete from public.quyen_vai_tro;

insert into public.quyen_vai_tro (vai_tro, ma_quyen) values
  ('ceo', 'cs.khach.xem'),
  ('ceo', 'cs.may.xem'),
  ('ceo', 'cs.ticket.xem'),
  ('ceo', 'cs.ticket.xem_tat_ca'),
  ('ceo', 'cs.bao_tri.xem'),
  ('ceo', 'cs.ky_thuat.lich_cua_toi'),
  ('ceo', 'cs.bao_cao.doanh_so'),
  ('ceo', 'cs.yeu_cau.xem'),
  ('ceo', 'sales.don.xem'),
  ('ceo', 'he_thong.nhan_su.xem'),
  ('ceo', 'he_thong.nhat_ky'),
  ('admin', 'cs.khach.xem'),
  ('admin', 'cs.khach.sua'),
  ('admin', 'cs.khach.xin_xoa'),
  ('admin', 'cs.khach.gop'),
  ('admin', 'cs.khach.duyet_cho'),
  ('admin', 'cs.khach.xin_xuat'),
  ('admin', 'cs.khach.duyet_xuat'),
  ('admin', 'cs.khach.duyet_xoa'),
  ('admin', 'cs.khach.xoa_hang_loat'),
  ('admin', 'cs.may.xem'),
  ('admin', 'cs.may.kich_hoat_bh'),
  ('admin', 'cs.may.lap_thu_doi'),
  ('admin', 'cs.serial.kho'),
  ('admin', 'cs.serial.duyet'),
  ('admin', 'cs.may.thay_loi'),
  ('admin', 'cs.may.trang_thai'),
  ('admin', 'cs.ticket.xem'),
  ('admin', 'cs.ticket.xem_tat_ca'),
  ('admin', 'cs.ticket.tao_sua'),
  ('admin', 'cs.ticket.chi_phi'),
  ('admin', 'cs.nhom_loi.cau_hinh'),
  ('admin', 'cs.nhom_loi.gan_ticket'),
  ('admin', 'cs.bao_tri.xem'),
  ('admin', 'cs.bao_tri.ghi_ket_qua'),
  ('admin', 'cs.bao_tri.tao_plan'),
  ('admin', 'cs.bao_tri.duyet_plan'),
  ('admin', 'cs.ky_thuat.lich_cua_toi'),
  ('admin', 'cs.ky_thuat.ho_so'),
  ('admin', 'cs.ky_thuat.xep_lich'),
  ('admin', 'cs.ky_thuat.tai_khoan'),
  ('admin', 'cs.bao_cao.xuat'),
  ('admin', 'cs.bao_cao.doanh_so'),
  ('admin', 'cs.yeu_cau.gui'),
  ('admin', 'cs.yeu_cau.xem'),
  ('admin', 'cs.yeu_cau.duyet'),
  ('admin', 'cs.yeu_cau.ap_thang'),
  ('admin', 'cs.hang_loat.cap_nhat'),
  ('admin', 'work.viec.xem_tao'),
  ('admin', 'work.viec.giao'),
  ('admin', 'work.luat_tu_sinh'),
  ('admin', 'sales.don.xem'),
  ('admin', 'sales.don.ghi'),
  ('admin', 'he_thong.nhan_su.xem'),
  ('admin', 'he_thong.nhan_su.sua'),
  ('admin', 'he_thong.nhan_su.mat_khau'),
  ('admin', 'he_thong.phan_quyen'),
  ('admin', 'he_thong.nhat_ky'),
  ('admin', 'he_thong.catalog'),
  ('admin', 'he_thong.kenh'),
  ('admin', 'he_thong.view_chung'),
  ('quan_tri_ht', 'cs.ky_thuat.lich_cua_toi'),
  ('quan_tri_ht', 'work.viec.xem_tao'),
  ('quan_tri_ht', 'work.viec.giao'),
  ('quan_tri_ht', 'he_thong.nhan_su.xem'),
  ('quan_tri_ht', 'he_thong.nhan_su.sua'),
  ('quan_tri_ht', 'he_thong.nhan_su.mat_khau'),
  ('quan_tri_ht', 'he_thong.phan_quyen'),
  ('quan_tri_ht', 'he_thong.nhat_ky'),
  ('quan_tri_ht', 'he_thong.catalog'),
  ('quan_tri_ht', 'he_thong.kenh'),
  ('quan_tri_ht', 'he_thong.view_chung'),
  ('quan_tri_ht', 'cs.nhom_loi.cau_hinh'),
  ('quan_tri_ht', 'cs.may.trang_thai'),
  ('kt_giam_doc', 'cs.ky_thuat.lich_cua_toi'),
  ('kt_giam_doc', 'work.viec.xem_tao'),
  ('kt_giam_doc', 'work.viec.giao'),
  ('ky_thuat', 'cs.ky_thuat.lich_cua_toi'),
  ('ky_thuat', 'work.viec.xem_tao'),
  ('ky_thuat', 'work.viec.giao'),
  ('ctv_lap_dat', 'cs.ky_thuat.lich_cua_toi'),
  ('ctv_lap_dat', 'work.viec.xem_tao'),
  ('ctv_lap_dat', 'work.viec.giao'),
  ('cs_manager', 'cs.khach.xem'),
  ('cs_manager', 'cs.khach.sua'),
  ('cs_manager', 'cs.khach.xin_xoa'),
  ('cs_manager', 'cs.khach.gop'),
  ('cs_manager', 'cs.khach.duyet_cho'),
  ('cs_manager', 'cs.khach.xin_xuat'),
  ('cs_manager', 'cs.khach.duyet_xuat'),
  ('cs_manager', 'cs.may.xem'),
  ('cs_manager', 'cs.may.kich_hoat_bh'),
  ('cs_manager', 'cs.may.lap_thu_doi'),
  ('cs_manager', 'cs.serial.kho'),
  ('cs_manager', 'cs.serial.duyet'),
  ('cs_manager', 'cs.may.thay_loi'),
  ('cs_manager', 'cs.may.trang_thai'),
  ('cs_manager', 'cs.ticket.xem'),
  ('cs_manager', 'cs.ticket.xem_tat_ca'),
  ('cs_manager', 'cs.ticket.tao_sua'),
  ('cs_manager', 'cs.ticket.chi_phi'),
  ('cs_manager', 'cs.nhom_loi.cau_hinh'),
  ('cs_manager', 'cs.nhom_loi.gan_ticket'),
  ('cs_manager', 'cs.bao_tri.xem'),
  ('cs_manager', 'cs.bao_tri.ghi_ket_qua'),
  ('cs_manager', 'cs.bao_tri.tao_plan'),
  ('cs_manager', 'cs.bao_tri.duyet_plan'),
  ('cs_manager', 'cs.ky_thuat.lich_cua_toi'),
  ('cs_manager', 'cs.ky_thuat.ho_so'),
  ('cs_manager', 'cs.ky_thuat.xep_lich'),
  ('cs_manager', 'cs.bao_cao.xuat'),
  ('cs_manager', 'cs.bao_cao.doanh_so'),
  ('cs_manager', 'cs.yeu_cau.gui'),
  ('cs_manager', 'cs.yeu_cau.xem'),
  ('cs_manager', 'cs.yeu_cau.duyet'),
  ('cs_manager', 'cs.yeu_cau.ap_thang'),
  ('cs_manager', 'cs.hang_loat.cap_nhat'),
  ('cs_manager', 'work.viec.xem_tao'),
  ('cs_manager', 'work.viec.giao'),
  ('cs_manager', 'work.luat_tu_sinh'),
  ('cs_manager', 'he_thong.kenh'),
  ('cs_manager', 'he_thong.view_chung'),
  ('cs', 'cs.khach.xem'),
  ('cs', 'cs.khach.sua'),
  ('cs', 'cs.khach.xin_xoa'),
  ('cs', 'cs.khach.xin_xuat'),
  ('cs', 'cs.may.xem'),
  ('cs', 'cs.may.kich_hoat_bh'),
  ('cs', 'cs.may.thay_loi'),
  ('cs', 'cs.ticket.xem'),
  ('cs', 'cs.ticket.tao_sua'),
  ('cs', 'cs.ticket.chi_phi'),
  ('cs', 'cs.bao_tri.xem'),
  ('cs', 'cs.bao_tri.ghi_ket_qua'),
  ('cs', 'cs.bao_tri.tao_plan'),
  ('cs', 'cs.ky_thuat.lich_cua_toi'),
  ('cs', 'cs.bao_cao.doanh_so'),
  ('cs', 'cs.yeu_cau.gui'),
  ('cs', 'work.viec.xem_tao'),
  ('cs', 'work.viec.giao'),
  ('cs', 'he_thong.kenh'),
  ('sales_manager', 'cs.ky_thuat.lich_cua_toi'),
  ('sales_manager', 'work.viec.xem_tao'),
  ('sales_manager', 'work.viec.giao'),
  ('sales_manager', 'sales.don.xem'),
  ('sales_manager', 'sales.don.ghi'),
  ('sales', 'cs.ky_thuat.lich_cua_toi'),
  ('sales', 'work.viec.xem_tao'),
  ('sales', 'work.viec.giao'),
  ('sales', 'sales.don.xem'),
  ('sales', 'sales.don.ghi'),
  ('marketing', 'cs.ky_thuat.lich_cua_toi'),
  ('marketing', 'work.viec.xem_tao'),
  ('marketing', 'work.viec.giao'),
  ('kho', 'cs.ky_thuat.lich_cua_toi'),
  ('kho', 'work.viec.xem_tao'),
  ('kho', 'work.viec.giao'),
  ('ke_toan', 'cs.ky_thuat.lich_cua_toi'),
  ('ke_toan', 'work.viec.xem_tao'),
  ('ke_toan', 'work.viec.giao'),
  ('tai_chinh', 'cs.ky_thuat.lich_cua_toi'),
  ('tai_chinh', 'work.viec.xem_tao'),
  ('tai_chinh', 'work.viec.giao')
on conflict do nothing;
